### ISSUE TITLE
i can no get gopherapi as explained 

### ISSUE THREAD

**Issue by noerosell** [friendsofgo/gopherapi#2]
`~/go/src/github.com$ env GIT_TERMINAL_PROMPT=1 go get -u github.com/friendsofgo/gopherapi
go: github.com/friendsofgo/gopherapi@v0.1.1: parsing go.mod: unexpected module path "github.com/friendsofgo/gopher-api"
go get: error loading module requirements`

go.mod contains `gopher-api` instead of `gopherapi`

**Comment by aperezg** [comment]
I've fixed the error, in the first place the package api was gopher-api but during development it was changed to gopherapi for simplicity, and I may forgot change all the paths! hehehe

Thanks for the collaboration!
